name: build

# La acción se va a correr ante un 'push' o 'pull request' en la rama 'develop'.
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest # Verificar que corra en Ubuntu es suficiente.
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 23+
      uses: actions/setup-java@v3
      with:
        java-version: '23.0.2+7'
        distribution: 'temurin'
        cache: maven
    - name: Set up Maven version
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.9
    - name: Build with Maven
      run: xvfb-run mvn -B package --file pom.xml